<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZl8gvev\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZl8gvev/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerZl8gvev.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerZl8gvev\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerZl8gvev\App_KernelDevDebugContainer([
    'container.build_hash' => 'Zl8gvev',
    'container.build_id' => 'ffa4e4d7',
    'container.build_time' => 1768689473,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZl8gvev');
